// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByBiGNRZshxIMPE3Eyw-qZKM15cBUd31w',
    appId: '1:1064722034163:android:d46a870b23f75e3469f686',
    messagingSenderId: '1064722034163',
    projectId: 'o-cash-9d21a',
    storageBucket: 'o-cash-9d21a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbbeI9PGhe1DVzQcsOUedzYQP0iY0VJzY',
    appId: '1:1064722034163:ios:2ffdbcd8cc9f689369f686',
    messagingSenderId: '1064722034163',
    projectId: 'o-cash-9d21a',
    storageBucket: 'o-cash-9d21a.firebasestorage.app',
    iosBundleId: 'com.example.ocash',
  );
}
